// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const buildDatabaseUrl = () => {
  const hasDbConfig =
    process.env.DB_HOST && process.env.DB_USER && process.env.DB_NAME;

  if (hasDbConfig) {
    const user = process.env.DB_USER || "";
    const password = process.env.DB_PASSWORD || "";
    const host = process.env.DB_HOST || "localhost";
    const port = process.env.DB_PORT || "5432";
    const database = process.env.DB_NAME || "postgres";
    const sslMode = process.env.DB_SSL_MODE || "require";

    return `postgresql://${encodeURIComponent(user)}:${encodeURIComponent(
      password
    )}@${host}:${port}/${database}?sslmode=${sslMode}`;
  }

  return process.env.DATABASE_URL || "";
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: buildDatabaseUrl(),
  },
});
